plugins {
    id 'com.android.application'
}

android {
    namespace 'com.jaffar.carinspection'
    compileSdk 35

    defaultConfig {
        applicationId "com.jaffar.carinspection"
        minSdk 23
        targetSdk 35
        versionCode 7
        versionName "7.0"
    }
}

dependencies {
    implementation 'androidx.core:core:1.13.1'
}
